// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
process.loadEnvFile()
import { defineConfig } from "prisma/config";

const db_url = process.env.ENVI === 'dev' ? process.env.DATABASE_URL : process.env.PROD_DB

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: db_url,
  },
});
